### ISSUE TITLE
新增端口  用户后，要自行重启ss

### ISSUE THREAD

**Issue by lovelyou** [edboffical/bsp#14]
bsp --start
bsp already start on pid 1584 [success]
root@S3:/etc# Traceback (most recent call last):
  File "/usr/bin/bsp", line 59, in <module>
    byte_lib.start()
  File "/usr/bin/byte_lib.py", line 153, in start
    traffic = get_traffic_web(port)+int(get_traffic(port))
  File "/usr/bin/byte_lib.py", line 27, in get_traffic_web
    return int(res)
ValueError: invalid literal for int() with base 10: '{"msg":"permission denied or lack of value"}'

**Comment by lovelyou** [comment]
想问大佬 是啥原因。

**Comment by lovelyou** [comment]
遇到一个问题是，先装SS  后装bsp 能新增，配制文件都正常更新，然后，SS 不能上了。然后重新安装SS,配制文件也能更新，SS要手动去 重启，配制文件才生效，我确定，配制文件，都对。

**Comment by lovelyou** [comment]
是不是我有什么细节上面，操作不对。

**Comment by edboffical** [comment]
是不是没有新增任何端口就bsp --start了

**Comment by edboffical** [comment]
bsp的配置文件能贴出来一下吗

**Comment by edboffical** [comment]
新增端口也不是立即生效的 配置文件里有个update_time 就是刷新重启ss的时间 如果过了这个时间还没生效 就是操作有问题

**Comment by lovelyou** [comment]
用的web 分支。新填端口后。弄的。。。bsp --start

**Comment by edboffical** [comment]
有出现程序奔溃的错误提示吗 web分支的话 你管理服务器和节点服务器的配置都要正确

**Comment by lovelyou** [comment]
{
    "bsp_key": "4j9i03mm92js83", 
    "get_traffic_url": "http://14.192.69.158/bsp/api-m/gt.php", 
    "limit_method": "web", 
    "mod_traffic_url": "http://14.192.69.158/bsp/api-m/ut.php", 
    "port_limit": {
        "2500": {
            "due_time": "1518772893", 
            "size": "200000"
        }, 
        "8081": {
            "due_time": "1518742559", 
            "size": "200000"
        }, 
        "8082": {
            "due_time": "1518743745", 
            "size": "200000"
        }, 
        "8083": {
            "due_time": "1518833070", 
            "size": "200000"
        }, 
        "8802": {
            "due_time": "1518743237", 
            "size": "200000"
        }, 
        "8803": {
            "due_time": "1518845242", 
            "size": "200000"
        }, 
        "8833": {
            "due_time": "1518741490", 
            "size": "200000"
        }
    }, 
    "ress_cmd": "/etc/init.d/shadowsocks restart", 
    "ssconf_path": "/etc/shadowsocks.json", 
    "update_time": "60"
}

**Comment by lovelyou** [comment]
仔细检查了，是配制文件的问题，已解决，请问大佬 ，这个是不是限制终端数？好像只有一个设置能链上。

**Comment by lovelyou** [comment]
好像不限制终端数。。。有问题再向大佬 请教

**Comment by edboffical** [comment]
谢谢支持 有什么问题随时在git上问就好

**Comment by lovelyou** [comment]
希望，把几个php里面的，psb_key 包含到一处。，有四处要改。。。。。改起来，很容易 忘记

**Comment by lovelyou** [comment]
ss_del   和SS_set  config  三个php文件的psb_key 能否，放在一个文件里面，include

**Comment by edboffical** [comment]
可以的你可以把ss_del和ss_set的放一个文件里然后引用 但是config的是在管理服务器上
