### ISSUE TITLE
流量用完，对应的账户没有删除啊！

### ISSUE THREAD

**Issue by rogerhanzhao** [edboffical/bsp#2]
流量用完，对应的账户没有删除啊！什么情况？

**Comment by edboffical** [comment]
没有start吧 bsp --start之后才会开始监听 仔细看下wiki哦

**Comment by rogerhanzhao** [comment]
start 了，新加的账户和端口，连不上，要重启服务器才可以，我配置流量只给1M 的，查看用了8M 了 账户还能用！

**Comment by rogerhanzhao** [comment]
[root@asia-server ~]# Traceback (most recent call last):
  File "/usr/bin/bsp", line 57, in <module>
    byte_lib.start()
  File "/usr/bin/byte_lib.py", line 112, in start
    if int(get_traffic(port))>=int(data[port]):
  File "/usr/bin/byte_lib.py", line 16, in get_traffic
    return int(math.floor(float(res)/math.pow(1000,2)))
ValueError: invalid literal for float(): 67880734
99682437
65442996
256


没注意，下面有个错误啥情况？

**Comment by rogerhanzhao** [comment]
目前发现就俩问题，增加端口和账户后-r  和--start 后都不管用，要重启服务器；
再就是流量用超过限制的，账户还在！

**Comment by rogerhanzhao** [comment]
[root@asia-server ~]# bsp -p 9001 -c
99M/10000M
[root@asia-server ~]# bsp -p 9000 -c
0M/10M
[root@asia-server ~]# bsp -p 8994 -c
65M/1M

**Comment by edboffical** [comment]
请把bsp的配置文件和ss的配置文件贴上来看下 另外你直接在ss的配置文件里增加用户是否会立即生效

**Comment by edboffical** [comment]
没有删除用户有可能是ss并没有重启 请检查bsp配置文件里 重启ss的命令    "ress_cmd":"/etc/init.d/shadowsocks-python restart"是否正确 另外 bsp流量更新时间默认180秒 "update_time":"180" 也就是流量用完之后可能不会立即删除对应账户 但是绝对不会超过180秒还没有删除账户 看你上面能用-c查询流量使用情况 说明规则和限额的添加并没有问题 请留意下我说的这两个问题

**Comment by rogerhanzhao** [comment]
没搞你的工具之前，我都是自己直接在SS配置文件里自己添加的，是生效的！
shadowsocks.json

{
    "dns_ipv6": false,
    "fast_open": false,
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "method": "aes-256-cfb",
    "obfs": "plain",
    "obfs_param": "",
    "port_password": {
        "8989": "nomater",
        "8990": "nomater",
        "8991": "nomater",
        "8992": "nomater",
        "8993": "nomater",
        "8994": "nomater",
        "9000": "qangqinglian",
        "9001": "alex"
    },
    "protocol": "origin",
    "protocol_param": "",
    "redirect": "",
    "server": "0.0.0.0",
    "server_ipv6": "::",




byte_ss.json


{
    "port_limit": {
        "": "1",
        "8989": "100",
        "8994": "1",
        "9000": "10",
        "9001": "10000"
    },
    "ress_cmd": "/etc/init.d/shadowsocks restart",
    "ssconf_path": "/etc/shadowsocks.json",
    "update_time": "180"
}
~
~
~
~
~
~
~
:

**Comment by rogerhanzhao** [comment]
配置文件都贴出来了，里面有些端口是我自己添加的不是通过bsb添加的

**Comment by edboffical** [comment]
bsp的配置有问题 port_limit里把第一行"": "1", 删掉，应该是这条错误配置导致bsp不正常运行

**Comment by rogerhanzhao** [comment]
这条我配置之处没的，是运行以后自动出来的
[root@asia-server etc]# cd init.d
[root@asia-server init.d]# ls
functions  netconsole  network  README  shadowsocks
[root@asia-server init.d]#

**Comment by edboffical** [comment]
{
"port_limit": {
"": "1",             ------把这条记录删了 然后wq保存
"8989": "100",
"8994": "1",
"9000": "10",
"9001": "10000"
},
"ress_cmd": "/etc/init.d/shadowsocks restart",
"ssconf_path": "/etc/shadowsocks.json",
"update_time": "180"
}

**Comment by rogerhanzhao** [comment]
删了
[root@asia-server byte]# vi byte_ss.json
[root@asia-server byte]# vi byte_ss.json
[root@asia-server byte]# bsa --restart
-bash: bsa: command not found
[root@asia-server byte]# bsa -r
-bash: bsa: command not found
[root@asia-server byte]# bsp --restart
Traceback (most recent call last):
  File "/usr/bin/bsp", line 7, in <module>
    opts, args = getopt.getopt(sys.argv[1:], "aAcdCjDORrp:s:P:", ["stop", "start","version"])
  File "/usr/lib64/python2.7/getopt.py", line 88, in getopt
    opts, args = do_longs(opts, args[0][2:], longopts, args[1:])
  File "/usr/lib64/python2.7/getopt.py", line 152, in do_longs
    has_arg, opt = long_has_args(opt, longopts)
  File "/usr/lib64/python2.7/getopt.py", line 169, in long_has_args
    raise GetoptError('option --%s not recognized' % opt, opt)
getopt.GetoptError: option --restart not recognized
[root@asia-server byte]# bsp -r
[root@asia-server byte]# bsp --start
bsp already start on pid 4984 [success]

**Comment by rogerhanzhao** [comment]
但是 这几个账户的流量归零了！

**Comment by edboffical** [comment]
因为你bsp -r之后iptables规则会重新添加一遍 之前记录的流量就重新开始记录了

**Comment by rogerhanzhao** [comment]
我之前用的是 firewalld ,每次要单独要单独添加端口，后来用你这个工具后，我就禁用了firewalld

**Comment by edboffical** [comment]
现在问题解决了吗

**Comment by rogerhanzhao** [comment]
解决了，为啥自动生成  "": "1", ------这条记录？

**Comment by edboffical** [comment]
可能是你之前手误打了个空命令 bsp -A 不会自己生成的

**Comment by rogerhanzhao** [comment]
有疑问： 重启shadowsock 服务后，之前端口的流量统计会归零么？
还是说bsp -r       bsp --start  后 流量归零重新统计了？

**Comment by edboffical** [comment]
重启ss不会清零 但是重启linux系统或者重启iptables会清零 bsp -r也会

**Comment by rogerhanzhao** [comment]
OK 明白了

**Comment by rogerhanzhao** [comment]
用完了自动删除后的端口 ，我看在JSON 文件里 端口还在，就是密码变成空了，bsp -r 之后 也不会恢复流量！

**Comment by edboffical** [comment]
你ss的问题吧 我自己Ubuntu和shadowsocks-python运行bsp一点都没问题

**Comment by rogerhanzhao** [comment]
我是CENT OS 7，  shadowsockR,   我这边是流量用完后，限额应该删除了，但是我查看shadowsock.json 文件，那个端口还在密码变成空了；

**Comment by edboffical** [comment]
不知道你这个问题在哪里 但是不影响啊 反正都要重新添加端口和规则 他会覆盖密码为空的那个端口的

**Comment by rogerhanzhao** [comment]
流量用完还是 不删除账户啊 ，呵呵!

**Comment by lovelyou** [comment]
大佬 ，我也遇到这个问题，流量值，设置很小的时候，流量用完，一会就可以正常删除，流量 值过的时候。。。。用完了也不删除，请问大佬 是不是，。。。python 某个数据类型，数值上限。。。所制。。。
