### ISSUE TITLE
bsp -p 8989 -P 123456 -s 100 -a -A –j    命令无法添加端口

### ISSUE THREAD

**Issue by liyongning16** [edboffical/bsp#29]
我试过手动重启ss，之后还是添加不进去

**Comment by liyongning16** [comment]
两个配置文件的端口都不一样
byte_ss.json

[root@vultr byte]# vim byte_ss.json 

{
    "port_limit": {
        "9002": "100",
        "9003": "100"
    },
    "ress_cmd": "/etc/init.d/shadowsocks restart",
    "ssconf_path": "/etc/shadowsocks/config.json",
    "update_time": "5"
}


shadowsocks的配置文件

[root@vultr shadowsocks]# vim config.json 

{
    "local_port": 1080,
    "method": "aes-256-cfb",
    "port_password": {
        "8989": "password0",
        "9002": "123456"
    },
    "server": "0.0.0.0",
    "timeout": 600
}

**Comment by liyongning16** [comment]
执行bsp --start时候出现这个

[root@vultr shadowsocks]# bsp --start
bsp already start on pid 18097 [success]
[root@vultr shadowsocks]# Traceback (most recent call last):
  File "/usr/bin/bsp", line 57, in <module>
    byte_lib.start()
  File "/usr/bin/byte_lib.py", line 119, in start
    if int(get_traffic(port))>=int(data[port]):
ValueError: invalid literal for int() with base 10: ''

**Comment by edboffical** [comment]
执行添加命令的时候没有出错信息吗 我建议你把两个配置文件里的端口配置内容都清空后再试试 配置文件地址千万不要搞错

**Comment by VincentSit** [comment]
出错是因为这里返回了一个空字符串。

https://github.com/edboffical/bsp/blob/513a011cc5586f77c069abe802a7941e60195192/byte_lib.py#L15

在 Python 中使用 `int()` 转换空字符串 `int("")` 就会抛出这个异常.

https://github.com/edboffical/bsp/blob/513a011cc5586f77c069abe802a7941e60195192/byte_lib.py#L119

改成 return 0 就可以了.
