### ISSUE TITLE
 No such file or directory: u'/etc/shadowsocks-python/config.json'

### ISSUE THREAD

**Issue by hongfenglt** [edboffical/bsp#4]
[root@host bsp]# bsp -p 7778 -P bnshdmm -s 500000 -a -A -j
Traceback (most recent call last):
  File "/usr/bin/bsp", line 32, in <module>
    byte_lib.a_json(ss_port,ss_pwd)
  File "/usr/bin/byte_lib.py", line 65, in a_json
    data=r_json()
  File "/usr/bin/byte_lib.py", line 42, in r_json
    with codecs.open(r_config()['ssconf_path']) as json_file:
  File "/usr/lib64/python2.6/codecs.py", line 881, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/etc/shadowsocks-python/config.json'

多账户配置是生效的。

**Comment by hongfenglt** [comment]
已经解决问题了，修改配置文件里的/etc/shadowsocks-python/config.json改为
/etc/shadowsocks.json
我的配置文件是这个。
正在测试流量用完自动删除。
感谢。

**Comment by hongfenglt** [comment]
我碰到的问题是，流量用完了，配置文件会自动清除端口，但是端口还能继续用。
必须重启服务才可以
ssserver -c /etc/shadowsocks.json -d restart
是我的ss的问题吗？

**Comment by edboffical** [comment]
bsp里的ss重启命令配置是否正确？请确认下

**Comment by hongfenglt** [comment]
应该是重启命令的问题，我修改了一下重启的命令，应该可以了。

**Comment by edboffical** [comment]
是的 应该是重启命令不对 我在着手加一个管理多个节点的功能

**Comment by hongfenglt** [comment]
嗯嗯。加油。

**Comment by edboffical** [comment]
那个wiki我写了 有兴趣可以看下
